# Generated by Django 4.2 on 2023-04-16 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.CharField(
                default="https://thumbs.dreamstime.com/b/no-image-available-icon-flat-vector-no-image-available-icon-flat-vector-illustration-132482953.jpg",
                max_length=1000,
            ),
        ),
    ]
