# Generated by Django 3.2 on 2023-04-25 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20230425_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='club',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
    ]
