# Generated by Django 3.2 on 2023-04-25 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20230425_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='club',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.club'),
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.CharField(default='https://thumbs.dreamstime.com/b/no-image-available-icon-flat-vector-no-image-available-icon-flat-vector-illustration-132482953.jpg', max_length=1000),
        ),
    ]
