# Generated by Django 3.2 on 2023-05-02 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0013_auto_20230430_2135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManagerGroup',
        ),
    ]
